const translations = {
  en: {
    nav:{system:'System',sprint:'Sprint',pricing:'Pricing',cta:'Book a call'},
    hero:{eyebrow:'YouTube growth system for music',title:'Your catalog deserves more than <em>random uploads.</em>',body:'YGROW turns music channels into structured growth engines—built to earn attention, reactivate catalog and improve revenue readiness.',cta:'Book a strategy call',secondary:'Explore the Sprint',trust:'Experience across iconic and contemporary music catalogs.'},
    visual:{label:'CATALOG SIGNAL',status:'Growth opportunity',discovery:'Discovery',sessions:'Sessions',assets:'Active assets',footer:'Catalog momentum'},
    proof:{kicker:'PROFESSIONAL CATALOG / CHANNEL EXPERIENCE',disclaimer:'Artist names illustrate professional catalog/channel experience and do not imply direct endorsement.'},
    problem:{title:'The algorithm is not a strategy.',body:'You upload. You wait. You check analytics. Nothing moves. The problem is rarely a lack of content—it is the system around it.',one:'Catalog buried without a discovery path',two:'Titles, thumbnails and playlists working alone',three:'Decisions made without actionable data',shiftA:'YouTube is not just a video platform.',shiftB:'It is a distribution system.'},
    system:{label:'THIS IS YGROW™',title:'One system.<br/>Three growth levers.',audienceTitle:'Grow audience',audienceBody:'Improve discovery across Browse, Suggested and Search with stronger packaging and structure.',catalogTitle:'Reactivate catalog',catalogBody:'Find hidden opportunities in assets you already own and build new paths into evergreen music.',revenueTitle:'Improve revenue readiness',revenueBody:'Build a channel foundation that supports monetization and compounds long-term growth.'},
    sprint:{title:'Clarity first.<br/>Then growth.',body:'Before a long-term plan, we diagnose the channel, map the opportunity and implement the highest-impact fixes.',link:'View packages',auditTitle:'Channel audit',auditBody:'A complete review of channel structure, content, packaging and monetization readiness.',mapTitle:'Catalog opportunity map',mapBody:'A ranked view of videos, songs and formats with overlooked growth potential.',quickTitle:'Quick wins implementation',quickBody:'Hands-on optimization of priority videos, playlists and channel touchpoints.',reportTitle:'Growth report',reportBody:'A practical 30- or 90-day roadmap with metrics, priorities and next steps.'},
    process:{audit:'Audit',strategy:'Strategy',optimization:'Optimization',scaling:'Scaling'},
    pricing:{title:'Choose your starting point.',body:'Transparent, focused engagements. No long-term commitment before we understand the opportunity.',starterFor:'INDEPENDENT ARTISTS',starterBody:'A focused diagnosis for emerging channels.',growthFor:'GROWTH-READY CHANNELS',growthBody:'The complete optimization foundation.',catalogFor:'MANAGERS & LABELS',catalogBody:'A deeper system for larger music catalogs.',basicAudit:'Basic channel audit',execReport:'Executive growth report',fiveVideos:'5 priority videos optimized',threeDays:'Delivered in 3–5 days',fullAudit:'Full channel audit',opportunityMap:'Catalog opportunity map',fifteenVideos:'15 priority videos optimized',playlist:'Playlist and channel structure',thirtyPlan:'30-day growth plan',deepAudit:'Deep channel and catalog audit',thirtyVideos:'30 priority videos optimized',catalogStrategy:'Catalog and playlist strategy',ninetyPlan:'90-day growth plan',select:'Select Sprint',recommended:'MOST POPULAR',note:'Prices exclude applicable taxes. Final billing currency is confirmed before engagement.'},
    break:{small:'YOU CAN KEEP WAITING FOR THE ALGORITHM.',title:'Or give your music<br/>a system built to move.'},
    apply:{title:'Let’s find the signal in your catalog.',body:'Tell us where the channel is today. We’ll use the first call to understand fit, priorities and the right starting point.',detailOneTitle:'20-minute strategy call',detailOneBody:'Focused, practical and no-pressure.',detailTwoTitle:'Channel-level diagnosis',detailTwoBody:'We review your goals before recommending a Sprint.'},
    form:{name:'Name',namePlaceholder:'Your name',email:'Work email',role:'Your role',choose:'Choose one',artist:'Artist',manager:'Manager',label:'Label',owner:'Catalog owner',other:'Other',channel:'YouTube channel URL',size:'Catalog size',objective:'Main objective',growth:'Audience growth',revenue:'Revenue',reactivation:'Catalog reactivation',launch:'Launch support',management:'Full management',submit:'Continue to Calendly',note:'Your details will prefill the booking flow. Scheduling is completed securely on Calendly.'},
    footer:{tagline:'YouTube Growth System<br/>for Music Catalogs.',navigate:'NAVIGATE',contact:'CONTACT'}
  },
  es: {
    nav:{system:'Sistema',sprint:'Sprint',pricing:'Precios',cta:'Agenda una llamada'},
    hero:{eyebrow:'Sistema de crecimiento en YouTube para música',title:'Tu catálogo merece más que <em>publicaciones al azar.</em>',body:'YGROW convierte canales musicales en motores de crecimiento estructurados para ganar atención, reactivar catálogo y mejorar su preparación para monetizar.',cta:'Agenda una llamada estratégica',secondary:'Conoce el Sprint',trust:'Experiencia con catálogos musicales icónicos y contemporáneos.'},
    visual:{label:'SEÑAL DEL CATÁLOGO',status:'Oportunidad de crecimiento',discovery:'Descubrimiento',sessions:'Sesiones',assets:'Activos vigentes',footer:'Impulso del catálogo'},
    proof:{kicker:'EXPERIENCIA PROFESIONAL EN CATÁLOGOS / CANALES',disclaimer:'Los nombres de artistas ilustran experiencia profesional en catálogos/canales y no implican endorsement directo.'},
    problem:{title:'El algoritmo no es una estrategia.',body:'Subes contenido. Esperas. Revisas analytics. Nada cambia. El problema rara vez es la falta de contenido: es el sistema que lo rodea.',one:'Catálogo enterrado sin una ruta de descubrimiento',two:'Títulos, thumbnails y playlists trabajando solos',three:'Decisiones sin datos accionables',shiftA:'YouTube no es solo una plataforma de video.',shiftB:'Es un sistema de distribución.'},
    system:{label:'ESTO ES YGROW™',title:'Un sistema.<br/>Tres palancas de crecimiento.',audienceTitle:'Crecer audiencia',audienceBody:'Mejoramos el descubrimiento en Browse, Suggested y Search con una estructura y presentación más sólidas.',catalogTitle:'Reactivar catálogo',catalogBody:'Encontramos oportunidades ocultas en los activos que ya tienes y creamos nuevas rutas hacia tu música evergreen.',revenueTitle:'Preparar para monetizar',revenueBody:'Construimos una base que impulsa la monetización y acumula crecimiento a largo plazo.'},
    sprint:{title:'Primero claridad.<br/>Después crecimiento.',body:'Antes de un plan a largo plazo, diagnosticamos el canal, mapeamos la oportunidad e implementamos los cambios de mayor impacto.',link:'Ver paquetes',auditTitle:'Auditoría de canal',auditBody:'Revisión completa de estructura, contenido, presentación y preparación para monetización.',mapTitle:'Mapa de oportunidades',mapBody:'Un ranking de videos, canciones y formatos con potencial de crecimiento desaprovechado.',quickTitle:'Implementación de quick wins',quickBody:'Optimización directa de videos, playlists y puntos de contacto prioritarios.',reportTitle:'Reporte de crecimiento',reportBody:'Un roadmap práctico de 30 o 90 días con métricas, prioridades y siguientes pasos.'},
    process:{audit:'Auditoría',strategy:'Estrategia',optimization:'Optimización',scaling:'Escalamiento'},
    pricing:{title:'Elige tu punto de partida.',body:'Proyectos transparentes y enfocados. Sin compromisos a largo plazo antes de entender la oportunidad.',starterFor:'ARTISTAS INDEPENDIENTES',starterBody:'Un diagnóstico enfocado para canales emergentes.',growthFor:'CANALES LISTOS PARA CRECER',growthBody:'La base completa de optimización.',catalogFor:'MANAGERS Y SELLOS',catalogBody:'Un sistema más profundo para catálogos grandes.',basicAudit:'Auditoría básica del canal',execReport:'Reporte ejecutivo de crecimiento',fiveVideos:'Optimización de 5 videos prioritarios',threeDays:'Entrega en 3–5 días',fullAudit:'Auditoría completa del canal',opportunityMap:'Mapa de oportunidades del catálogo',fifteenVideos:'Optimización de 15 videos prioritarios',playlist:'Estructura de playlists y canal',thirtyPlan:'Plan de crecimiento de 30 días',deepAudit:'Auditoría profunda de canal y catálogo',thirtyVideos:'Optimización de 30 videos prioritarios',catalogStrategy:'Estrategia de catálogo y playlists',ninetyPlan:'Plan de crecimiento de 90 días',select:'Elegir Sprint',recommended:'MÁS POPULAR',note:'Los precios no incluyen los impuestos aplicables. La moneda final se confirma antes de iniciar.'},
    break:{small:'PUEDES SEGUIR ESPERANDO AL ALGORITMO.',title:'O darle a tu música<br/>un sistema para avanzar.'},
    apply:{title:'Encontremos la señal dentro de tu catálogo.',body:'Cuéntanos dónde está hoy tu canal. Usaremos la primera llamada para entender el encaje, las prioridades y el mejor punto de partida.',detailOneTitle:'Llamada estratégica de 20 minutos',detailOneBody:'Enfocada, práctica y sin presión.',detailTwoTitle:'Diagnóstico a nivel canal',detailTwoBody:'Revisamos tus objetivos antes de recomendar un Sprint.'},
    form:{name:'Nombre',namePlaceholder:'Tu nombre',email:'Email de trabajo',role:'Tu rol',choose:'Elige una opción',artist:'Artista',manager:'Manager',label:'Sello',owner:'Dueño de catálogo',other:'Otro',channel:'URL del canal de YouTube',size:'Tamaño del catálogo',objective:'Objetivo principal',growth:'Crecimiento de audiencia',revenue:'Revenue',reactivation:'Reactivación de catálogo',launch:'Apoyo de lanzamiento',management:'Gestión integral',submit:'Continuar a Calendly',note:'Tus datos se usarán para prellenar la reservación. La agenda se completa de forma segura en Calendly.'},
    footer:{tagline:'Sistema de crecimiento en YouTube<br/>para catálogos musicales.',navigate:'NAVEGAR',contact:'CONTACTO'}
  }
};

const prices={en:{starter:'300',growth:'750',catalog:'1,500',currency:'$',code:'USD'},es:{starter:'5,900',growth:'14,900',catalog:'29,900',currency:'$',code:'MXN'}};
let locale=localStorage.getItem('ygrow-locale')||((navigator.language||'').startsWith('es')?'es':'en');

function get(obj,path){return path.split('.').reduce((value,key)=>value?.[key],obj)}
function setLocale(next){locale=next;localStorage.setItem('ygrow-locale',next);document.documentElement.lang=next;document.title=next==='es'?'YGROW™ — Crecimiento en YouTube para catálogos musicales':'YGROW™ — YouTube Growth for Music Catalogs';document.querySelectorAll('[data-i18n]').forEach(el=>{const value=get(translations[next],el.dataset.i18n);if(value)el.innerHTML=value});document.querySelectorAll('[data-placeholder]').forEach(el=>{el.placeholder=get(translations[next],el.dataset.placeholder)||el.placeholder});document.querySelectorAll('[data-price]').forEach(el=>el.textContent=prices[next][el.dataset.price]);document.querySelectorAll('[data-currency]').forEach(el=>el.textContent=prices[next].currency);document.querySelectorAll('[data-code]').forEach(el=>el.textContent=prices[next].code);document.querySelectorAll('.locale-btn').forEach(btn=>{const active=btn.dataset.locale===next;btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',String(active))})}
document.querySelectorAll('.locale-btn').forEach(btn=>btn.addEventListener('click',()=>setLocale(btn.dataset.locale)));
document.querySelectorAll('[data-plan]').forEach(link=>link.addEventListener('click',()=>{document.querySelector('#plan').value=link.dataset.plan}));

const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));

document.querySelector('#lead-form').addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.currentTarget);const profile=Object.fromEntries(form.entries());sessionStorage.setItem('ygrow-lead-profile',JSON.stringify({...profile,locale}));const params=new URLSearchParams({name:profile.name,email:profile.email,a1:profile.role,a2:profile.channel,a3:profile.size,a4:profile.objective,a5:profile.plan,utm_source:'ygrow_website',utm_medium:'qualified_lead',utm_campaign:locale==='es'?'mx_launch':'global_launch'});window.open(`https://calendly.com/YGROW?${params.toString()}`,'_blank','noopener,noreferrer')});
setLocale(locale);
